# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2b3dfdcb8e57dd51b4bdf5b618a2ae60d8cb1331375887e9a102e9ab44158ca5783d039e3921efef45b932ca7baf2d95f729c0dac7ac013f0304a233ab687b2d

test:
  secret_key_base: cf83f1e7a0d68016e1887d4b2c2312a0d2d5b29e4671685d0677c1bc65f27a5264d7c4cbad86aa7f64e385700f5ff25a1d7b7599e2eae58dc29b319ea7e594d9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
