# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.find_or_create_by([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.find_or_create_by(name: 'Emanuel', city: cities.first)
################################## CIS MAJOR #####################################

@User = User.find_or_create_by(name: "Lily Wang", pennkey: "lilw")
@User.majors.find_or_create_by(name: "Computer Science (CIS)", total_required:40)

@CIS = Major.find_or_create_by(name: "Computer Science (CIS)", total_required:40)

@Math = @CIS.curriculum_fields.find_or_create_by(name:"Math" , total_required:6)
@NatSci = @CIS.curriculum_fields.find_or_create_by(name:"Natural Science" , total_required:4)
@Eng = @CIS.curriculum_fields.find_or_create_by(name:"Engineering" , total_required:14)
@TechElec = @CIS.curriculum_fields.find_or_create_by(name:"Tech Elective" , total_required:6)
@SSandH = @CIS.curriculum_fields.find_or_create_by(name:"Social Science and Humanities" , total_required:7)
@FreeElec =@CIS.curriculum_fields.find_or_create_by(name:"Free Elective" , total_required:3)

@Math.requirements.find_or_create_by(name: "MATH 104", credits: 1)
@Math.requirements.find_or_create_by(name: "MATH 114", credits: 1)
@Math.requirements.find_or_create_by(name: "CIS 160", credits: 1)
@Math.requirements.find_or_create_by(name: "CIS 261 or ESE 301 or ENM 231 or STAT 430", credits: 1)
@Math.requirements.find_or_create_by(name: "Math Elective", credits: 1)
@Math.requirements.find_or_create_by(name: "Math Elective", credits: 1)

@NatSci.requirements.find_or_create_by(name: "PHYS 140 or PHYS 150", credits: 1)
@NatSci.requirements.find_or_create_by(name: "Natural Science", credits: 1)
@NatSci.requirements.find_or_create_by(name: "Natural Science/Lab Requirement", credits: 1)

@Eng.requirements.find_or_create_by(name:"CIS 110", credits: 1)
@Eng.requirements.find_or_create_by(name:"CIS 120", credits: 1)
@Eng.requirements.find_or_create_by(name:"CIS 121", credits: 1)
@Eng.requirements.find_or_create_by(name:"CIS 240", credits: 1)
@Eng.requirements.find_or_create_by(name:"CIS 262", credits: 1)
@Eng.requirements.find_or_create_by(name:"CIS 320", credits: 1)
@Eng.requirements.find_or_create_by(name:"One of: CIS 277, CIS 341, CIS 450, CIS 455, CIS 553, ESE 350, CIS 350", credits: 1)
@Eng.requirements.find_or_create_by(name:"CIS 371", credits: 1)
@Eng.requirements.find_or_create_by(name:"CIS 380", credits: 1)
@Eng.requirements.find_or_create_by(name:"CIS 400", credits: 1)
@Eng.requirements.find_or_create_by(name:"CIS 401", credits: 1)
@Eng.requirements.find_or_create_by(name:"CIS Elective", credits: 1)
@Eng.requirements.find_or_create_by(name:"CIS Elective", credits: 1)
@Eng.requirements.find_or_create_by(name:"CIS Elective", credits: 1)

@TechElec.requirements.find_or_create_by(name:"Tech Elective (Engineering)", credits: 1)
@TechElec.requirements.find_or_create_by(name:"Tech Elective (Engineering)", credits: 1)
@TechElec.requirements.find_or_create_by(name:"Tech Elective", credits: 1)
@TechElec.requirements.find_or_create_by(name:"Tech Elective", credits: 1)
@TechElec.requirements.find_or_create_by(name:"Tech Elective", credits: 1)
@TechElec.requirements.find_or_create_by(name:"Tech Elective", credits: 1)

@SSandH.requirements.find_or_create_by(name:"Social Science", credits: 1)
@SSandH.requirements.find_or_create_by(name:"Social Science", credits: 1)
@SSandH.requirements.find_or_create_by(name:"Humanities", credits: 1)
@SSandH.requirements.find_or_create_by(name:"Humanities", credits: 1)
@SSandH.requirements.find_or_create_by(name:"SS or H", credits: 1)
@SSandH.requirements.find_or_create_by(name:"SS, H, or TBS", credits: 1)
@SSandH.requirements.find_or_create_by(name:"SS, H, or TBS", credits: 1)

@FreeElec.requirements.find_or_create_by(name:"Free Elective", credits: 1)
@FreeElec.requirements.find_or_create_by(name:"Free Elective", credits: 1)
@FreeElec.requirements.find_or_create_by(name:"Free Elective", credits: 1)

###################### MEAM MAJOR ################################
@MEAM = Major.find_or_create_by(name: "Mechanical Engineering and Applied Mechanics", total_required:40)

@Math = @MEAM.curriculum_fields.find_or_create_by!(name:"Math" , total_required:5)
@NatSci = @MEAM.curriculum_fields.find_or_create_by(name:"Natural Science" , total_required:5)
@Eng = @MEAM.curriculum_fields.find_or_create_by(name:"Engineering" , total_required:10)
@ProfElec = @MEAM.curriculum_fields.find_or_create_by(name:"Professional Electives" , total_required:10)
@SSandH = @MEAM.curriculum_fields.find_or_create_by(name:"Social Science and Humanities" , total_required:7)
@FreeElec =@MEAM.curriculum_fields.find_or_create_by(name:"Free Elective" , total_required:3)

@Math.requirements.find_or_create_by(name: "MATH 104", credits: 1)
@Math.requirements.find_or_create_by(name: "MATH 114", credits: 1)
@Math.requirements.find_or_create_by(name: "MATH 240", credits: 1)
@Math.requirements.find_or_create_by(name: "ENM 251 or MATH 241", credits: 1)
@Math.requirements.find_or_create_by(name: "Mathematics (EAS 205 recommended)", credits: 1)

@NatSci.requirements.find_or_create_by(name: "MEAM 110 and MEAM 147 (0.5) or PHYS 150", credits: 1)
@NatSci.requirements.find_or_create_by(name: "PHYS 151", credits: 1)
@NatSci.requirements.find_or_create_by(name: "CHEM 101", credits: 1)
@NatSci.requirements.find_or_create_by(name: "CHEM 053", credits: 0.5)
@NatSci.requirements.find_or_create_by(name: "Natural Science (BIOL 101, 121 and PHYS 280 recommended)", credits: 1)

@Eng.requirements.find_or_create_by(name:"MEAM 203", credits: 1)
@Eng.requirements.find_or_create_by(name:"MEAM 210", credits: 1)
@Eng.requirements.find_or_create_by(name:"MEAM 211", credits: 1)
@Eng.requirements.find_or_create_by(name:"MEAM 247", credits: 0.5)
@Eng.requirements.find_or_create_by(name:"MEAM 248", credits: 0.5)
@Eng.requirements.find_or_create_by(name:"MEAM 302", credits: 1)
@Eng.requirements.find_or_create_by(name:"MEAM 321", credits: 1)
@Eng.requirements.find_or_create_by(name:"MEAM 333", credits: 1)
@Eng.requirements.find_or_create_by(name:"MEAM 347", credits: 1)
@Eng.requirements.find_or_create_by(name:"MEAM 348", credits: 1)
@Eng.requirements.find_or_create_by(name:"MEAM 354", credits: 1)

@ProfElec.requirements.find_or_create_by(name:"MEAM 445 (Design Project I", credits: 1)
@ProfElec.requirements.find_or_create_by(name:"MEAM 445 (Design Project II", credits: 1)
@ProfElec.requirements.find_or_create_by(name:"MEAM Upper Level", credits: 1)
@ProfElec.requirements.find_or_create_by(name:"MEAM Upper Level", credits: 1)
@ProfElec.requirements.find_or_create_by(name:"MEAM Upper Level", credits: 1)
@ProfElec.requirements.find_or_create_by(name:"Professional Elective", credits: 1)
@ProfElec.requirements.find_or_create_by(name:"Professional Elective", credits: 1)
@ProfElec.requirements.find_or_create_by(name:"Professional Elective", credits: 1)
@ProfElec.requirements.find_or_create_by(name:"Professional Elective", credits: 1)

@SSandH.requirements.find_or_create_by(name:"Social Science", credits: 1)
@SSandH.requirements.find_or_create_by(name:"Social Science", credits: 1)
@SSandH.requirements.find_or_create_by(name:"Humanities", credits: 1)
@SSandH.requirements.find_or_create_by(name:"Humanities", credits: 1)
@SSandH.requirements.find_or_create_by(name:"SS or H", credits: 1)
@SSandH.requirements.find_or_create_by(name:"SS, H, or TBS", credits: 1)
@SSandH.requirements.find_or_create_by(name:"SS, H, or TBS", credits: 1)

@FreeElec.requirements.find_or_create_by(name:"Free Elective", credits: 1)
@FreeElec.requirements.find_or_create_by(name:"Free Elective", credits: 1)
@FreeElec.requirements.find_or_create_by(name:"Free Elective", credits: 1)

###########################CBE############################
@CBE = Major.find_or_create_by(name: "Chemical Biomolecular Engineering", total_required:41)

@Math = @CBE.curriculum_fields.find_or_create_by!(name:"Math" , total_required:4)
@NatSci = @CBE.curriculum_fields.find_or_create_by(name:"Natural Science" , total_required:9)
@Eng = @CBE.curriculum_fields.find_or_create_by(name:"Engineering" , total_required:14)
@TechElec = @CBE.curriculum_fields.find_or_create_by(name:"Tech Elective" , total_required:4)
@SSandH = @CBE.curriculum_fields.find_or_create_by(name:"Social Science and Humanities" , total_required:7)
@FreeElec =@CBE.curriculum_fields.find_or_create_by(name:"Free Elective" , total_required:3)

@Math.requirements.find_or_create_by(name: "MATH 104", credits: 1)
@Math.requirements.find_or_create_by(name: "MATH 114", credits: 1)
@Math.requirements.find_or_create_by(name: "MATH 240", credits: 1)
@Math.requirements.find_or_create_by(name: "MATH 241", credits: 1)

@NatSci.requirements.find_or_create_by(name: "PHYS 140 or PHYS 150", credits: 1.5)
@NatSci.requirements.find_or_create_by(name: "PHYS 141 or PHYS 151", credits: 1.5)
@NatSci.requirements.find_or_create_by(name: "CHEM 101", credits: 1)
@NatSci.requirements.find_or_create_by(name: "CHEM 053", credits: 0.5)
@NatSci.requirements.find_or_create_by(name: "CHEM 102", credits: 1)
@NatSci.requirements.find_or_create_by(name: "CHEM 054", credits: 0.5)
@NatSci.requirements.find_or_create_by(name: "CHEM 221 or MSE 221", credits: 1)
@NatSci.requirements.find_or_create_by(name: "CHEM 241", credits: 1)
@NatSci.requirements.find_or_create_by(name: "CHEM 242 or MSE 251", credits: 1)

@Eng.requirements.find_or_create_by(name:"EAS 105", credits: 1)
@Eng.requirements.find_or_create_by(name:"CBE 160", credits: 1)
@Eng.requirements.find_or_create_by(name:"CBE 230", credits: 1)
@Eng.requirements.find_or_create_by(name:"CBE 231", credits: 1)
@Eng.requirements.find_or_create_by(name:"CBE 350", credits: 1)
@Eng.requirements.find_or_create_by(name:"CBE 351", credits: 1)
@Eng.requirements.find_or_create_by(name:"CBE 353", credits: 1)
@Eng.requirements.find_or_create_by(name:"CBE 371", credits: 1)
@Eng.requirements.find_or_create_by(name:"CBE 400", credits: 1)
@Eng.requirements.find_or_create_by(name:"CBE 410", credits: 1)
@Eng.requirements.find_or_create_by(name:"CBE 451", credits: 1)
@Eng.requirements.find_or_create_by(name:"CBE 459", credits: 1)
@Eng.requirements.find_or_create_by(name:"CBE 460", credits: 1)
@Eng.requirements.find_or_create_by(name:"CBE Elective", credits: 1)
@Eng.requirements.find_or_create_by(name:"CBE Elective", credits: 1)

@TechElec.requirements.find_or_create_by(name:"Engineering", credits: 1)
@TechElec.requirements.find_or_create_by(name:"Tech Elective", credits: 1)
@TechElec.requirements.find_or_create_by(name:"Tech Elective", credits: 1)
@TechElec.requirements.find_or_create_by(name:"CBE 480 or CHEM 223 or CHEM 245", credits: 1)

@SSandH.requirements.find_or_create_by(name:"Social Science", credits: 1)
@SSandH.requirements.find_or_create_by(name:"Social Science", credits: 1)
@SSandH.requirements.find_or_create_by(name:"Humanities", credits: 1)
@SSandH.requirements.find_or_create_by(name:"Humanities", credits: 1)
@SSandH.requirements.find_or_create_by(name:"SS or H", credits: 1)
@SSandH.requirements.find_or_create_by(name:"SS, H, or TBS", credits: 1)
@SSandH.requirements.find_or_create_by(name:"SS, H, or TBS", credits: 1)

@FreeElec.requirements.find_or_create_by(name:"Free Elective", credits: 1)
@FreeElec.requirements.find_or_create_by(name:"Free Elective", credits: 1)
@FreeElec.requirements.find_or_create_by(name:"Free Elective", credits: 1)

###########################BE############################
@BE = Major.find_or_create_by(name: "Bioengineering Engineering", total_required:40.5)

@Math = @BE.curriculum_fields.find_or_create_by!(name:"Math" , total_required:5)
@NatSci = @BE.curriculum_fields.find_or_create_by(name:"Natural Science" , total_required:7.5)
@Eng = @BE.curriculum_fields.find_or_create_by(name:"Engineering" , total_required:16)
@TechElec = @BE.curriculum_fields.find_or_create_by(name:"Technical Electives" , total_required:2)
@SSandH = @BE.curriculum_fields.find_or_create_by(name:"Social Science and Humanities" , total_required:7)
@FreeElec =@BE.curriculum_fields.find_or_create_by(name:"Free Elective" , total_required:3)

@Math.requirements.find_or_create_by(name: "MATH 104", credits: 1)
@Math.requirements.find_or_create_by(name: "MATH 114", credits: 1)
@Math.requirements.find_or_create_by(name: "MATH 240", credits: 1)
@Math.requirements.find_or_create_by(name: "MATH 241", credits: 1)
@Math.requirements.find_or_create_by(name: "ENM 321", credits: 1)

@NatSci.requirements.find_or_create_by(name: "PHYS 93, 140, 150, 170", credits: 1)
@NatSci.requirements.find_or_create_by(name: "PHYS 94, 141, 151, 171", credits: 1)
@NatSci.requirements.find_or_create_by(name: "CHEM 15, 91, 101", credits: 1)
@NatSci.requirements.find_or_create_by(name: "CHEM 053", credits: 0.5)
@NatSci.requirements.find_or_create_by(name: "CHEM 16, 102", credits: 1)
@NatSci.requirements.find_or_create_by(name: "CHEM 054", credits: 0.5)
@NatSci.requirements.find_or_create_by(name: "BIOL 121", credits: 1)
@NatSci.requirements.find_or_create_by(name: "BIOL 123", credits: 1)
@NatSci.requirements.find_or_create_by(name: "BIOL 202, 215, or 221", credits: 1)

@Eng.requirements.find_or_create_by(name:"BE 100", credits: 1)
@Eng.requirements.find_or_create_by(name:"BE 101", credits: 1)
@Eng.requirements.find_or_create_by(name:"EAS/ENGR 105", credits: 1)
@Eng.requirements.find_or_create_by(name:"BE 200", credits: 1)
@Eng.requirements.find_or_create_by(name:"BE 220", credits: 1)
@Eng.requirements.find_or_create_by(name:"BE 301", credits: 1)
@Eng.requirements.find_or_create_by(name:"BE 305", credits: 1)
@Eng.requirements.find_or_create_by(name:"BE 306", credits: 1)
@Eng.requirements.find_or_create_by(name:"BE 309", credits: 1)
@Eng.requirements.find_or_create_by(name:"BE 310", credits: 1)
@Eng.requirements.find_or_create_by(name:"BE 324", credits: 1)
@Eng.requirements.find_or_create_by(name:"BE 350", credits: 1)
@Eng.requirements.find_or_create_by(name:"BE 495", credits: 1)
@Eng.requirements.find_or_create_by(name:"BE 496", credits: 1)
@Eng.requirements.find_or_create_by(name:"BE Elective (400 or 500 Level)", credits: 1)
@Eng.requirements.find_or_create_by(name:"BE Elective (400 or 500 Level)", credits: 1)
@Eng.requirements.find_or_create_by(name:"Engineering Elective", credits: 1)

@TechElec.requirements.find_or_create_by(name:"Engineering, Math, Science", credits: 1)
@TechElec.requirements.find_or_create_by(name:"Engineering, Math, Science", credits: 1)

@SSandH.requirements.find_or_create_by(name:"Social Science", credits: 1)
@SSandH.requirements.find_or_create_by(name:"Social Science", credits: 1)
@SSandH.requirements.find_or_create_by(name:"Humanities", credits: 1)
@SSandH.requirements.find_or_create_by(name:"Humanities", credits: 1)
@SSandH.requirements.find_or_create_by(name:"SS or H", credits: 1)
@SSandH.requirements.find_or_create_by(name:"SS, H, or TBS", credits: 1)
@SSandH.requirements.find_or_create_by(name:"SS, H, or TBS", credits: 1)

@FreeElec.requirements.find_or_create_by(name:"Free Elective", credits: 1)
@FreeElec.requirements.find_or_create_by(name:"Free Elective", credits: 1)
@FreeElec.requirements.find_or_create_by(name:"Free Elective", credits: 1)

###########################CMPE############################

@CMPE = Major.find_or_create_by(name: "Computer Engineering", total_required:40)

@MathandNatSci = @CMPE.curriculum_fields.find_or_create_by(name:"Math and Natural Science" , total_required:10.5)
@Eng = @CMPE.curriculum_fields.find_or_create_by(name:"Engineering" , total_required:17)
@TechElec = @CMPE.curriculum_fields.find_or_create_by(name:"Tech Elective" , total_required:2.5)
@SSandH = @CMPE.curriculum_fields.find_or_create_by(name:"Social Science and Humanities" , total_required:7)
@FreeElec =@CMPE.curriculum_fields.find_or_create_by(name:"Free Elective" , total_required:3)

@MathandNatSci.requirements.find_or_create_by(name: "MATH 104", credits: 1)
@MathandNatSci.requirements.find_or_create_by(name: "MATH 114", credits: 1)
@MathandNatSci.requirements.find_or_create_by(name: "MATH 240", credits: 1)
@MathandNatSci.requirements.find_or_create_by(name: "ESE 301, CIS 261, STAT 430, MATH 430, or ENM 321", credits: 1)
@MathandNatSci.requirements.find_or_create_by(name: "CIS 160", credits: 1)
@MathandNatSci.requirements.find_or_create_by(name: "PHYS 150 or PHYS 170", credits: 1.5)
@MathandNatSci.requirements.find_or_create_by(name: "PHYS 151 or PHYS 171", credits: 1.5)
@MathandNatSci.requirements.find_or_create_by(name: "CHEM 101/53, BIOL 101, or BIOL 121", credits: 1.5)
@MathandNatSci.requirements.find_or_create_by(name: "Math or Natural Science Elective", credits: 1)

@Eng.requirements.find_or_create_by(name:"CIS 120", credits: 1)
@Eng.requirements.find_or_create_by(name:"CIS 121", credits: 1)
@Eng.requirements.find_or_create_by(name:"ESE 170", credits: 1)
@Eng.requirements.find_or_create_by(name:"ESE 171", credits: 0.5)
@Eng.requirements.find_or_create_by(name:"ESE 205", credits: 0.5)
@Eng.requirements.find_or_create_by(name:"ESE 215", credits: 1)
@Eng.requirements.find_or_create_by(name:"CIS 240", credits: 1)
@Eng.requirements.find_or_create_by(name:"ESE 250", credits: 0.5)
@Eng.requirements.find_or_create_by(name:"ESE 350", credits: 1.5)
@Eng.requirements.find_or_create_by(name:"CIS 350", credits: 1)
@Eng.requirements.find_or_create_by(name:"ESE 370", credits: 1)
@Eng.requirements.find_or_create_by(name:"CIS 371", credits: 1)
@Eng.requirements.find_or_create_by(name:"CIS 380", credits: 1)
@Eng.requirements.find_or_create_by(name:"CIS 441", credits: 1)
@Eng.requirements.find_or_create_by(name:"ESE 404 or CIS 553", credits: 1)
@Eng.requirements.find_or_create_by(name:"CIS 455 or CIS 565 or CIS 534", credits: 1)
@Eng.requirements.find_or_create_by(name:"CIS 400 or ESE 450", credits: 1)
@Eng.requirements.find_or_create_by(name:"CIS 401 or ESE 451", credits: 1)

@TechElec.requirements.find_or_create_by(name:"Tech Elective", credits: 1)
@TechElec.requirements.find_or_create_by(name:"Tech Elective", credits: 1)
@TechElec.requirements.find_or_create_by(name:"Tech Elective", credits: 0.5)

@SSandH.requirements.find_or_create_by(name:"Social Science", credits: 1)
@SSandH.requirements.find_or_create_by(name:"Social Science", credits: 1)
@SSandH.requirements.find_or_create_by(name:"Humanities", credits: 1)
@SSandH.requirements.find_or_create_by(name:"Humanities", credits: 1)
@SSandH.requirements.find_or_create_by(name:"SS or H", credits: 1)
@SSandH.requirements.find_or_create_by(name:"SS, H, or TBS", credits: 1)
@SSandH.requirements.find_or_create_by(name:"SS, H, or TBS", credits: 1)

@FreeElec.requirements.find_or_create_by(name:"Free Elective", credits: 1)
@FreeElec.requirements.find_or_create_by(name:"Free Elective", credits: 1)
@FreeElec.requirements.find_or_create_by(name:"Free Elective", credits: 1)

###########################DMD############################

@DMD = Major.find_or_create_by(name: "Digital Media Design", total_required:40)

@MathandNatSci = @DMD.curriculum_fields.find_or_create_by!(name:"Math and Natural Science" , total_required:10)
@Eng = @DMD.curriculum_fields.find_or_create_by(name:"Engineering" , total_required:12)
@DMDElec = @DMD.curriculum_fields.find_or_create_by(name:"DMD Electives" , total_required:9)
@SSandH = @DMD.curriculum_fields.find_or_create_by(name:"Social Science and Humanities" , total_required:7)
@FreeElec =@DMD.curriculum_fields.find_or_create_by(name:"Free Elective" , total_required:2)

@MathandNatSci.requirements.find_or_create_by(name: "MATH 104", credits: 1)
@MathandNatSci.requirements.find_or_create_by(name: "MATH 114", credits: 1)
@MathandNatSci.requirements.find_or_create_by(name: "CIS 160", credits: 1)
@MathandNatSci.requirements.find_or_create_by(name: "CIS 262", credits: 1)
@MathandNatSci.requirements.find_or_create_by(name: "EAS 205", credits: 1)
@MathandNatSci.requirements.find_or_create_by(name: "Natural Science", credits: 1)
@MathandNatSci.requirements.find_or_create_by(name: "Natural Science", credits: 1)
@MathandNatSci.requirements.find_or_create_by(name: "Math or Natural Science", credits: 1)
@MathandNatSci.requirements.find_or_create_by(name: "Natural Science", credits: 1)
@MathandNatSci.requirements.find_or_create_by(name: "Natural Science", credits: 1)

@Eng.requirements.find_or_create_by(name:"CIS 110", credits: 1)
@Eng.requirements.find_or_create_by(name:"CIS 120", credits: 1)
@Eng.requirements.find_or_create_by(name:"CIS 121", credits: 1)
@Eng.requirements.find_or_create_by(name:"CIS 240", credits: 1)
@Eng.requirements.find_or_create_by(name:"CIS 277", credits: 1)
@Eng.requirements.find_or_create_by(name:"CIS 320", credits: 1)
@Eng.requirements.find_or_create_by(name:"CIS 460", credits: 1)
@Eng.requirements.find_or_create_by(name:"CIS 462 or CIS 455", credits: 1)
@Eng.requirements.find_or_create_by(name:"CIS 497", credits: 1)
@Eng.requirements.find_or_create_by(name:"CIS 300 level or above", credits: 1)
@Eng.requirements.find_or_create_by(name:"CIS 300 level or above", credits: 1)
@Eng.requirements.find_or_create_by(name:"CIS Elective", credits: 1)

@DMDElec.requirements.find_or_create_by(name:"FNAR 123 or 124", credits: 1)
@DMDElec.requirements.find_or_create_by(name:"FNAR 235 or 236", credits: 1)
@DMDElec.requirements.find_or_create_by(name:"DMD Elective", credits: 1)
@DMDElec.requirements.find_or_create_by(name:"DMD Elective", credits: 1)
@DMDElec.requirements.find_or_create_by(name:"DMD Elective", credits: 1)
@DMDElec.requirements.find_or_create_by(name:"DMD Elective", credits: 1)
@DMDElec.requirements.find_or_create_by(name:"DMD Elective", credits: 1)
@DMDElec.requirements.find_or_create_by(name:"DMD Elective", credits: 1)
@DMDElec.requirements.find_or_create_by(name:"DMD Elective", credits: 1)

@SSandH.requirements.find_or_create_by(name:"Social Science", credits: 1)
@SSandH.requirements.find_or_create_by(name:"Social Science", credits: 1)
@SSandH.requirements.find_or_create_by(name:"Humanities", credits: 1)
@SSandH.requirements.find_or_create_by(name:"Humanities", credits: 1)
@SSandH.requirements.find_or_create_by(name:"SS or H", credits: 1)
@SSandH.requirements.find_or_create_by(name:"SS, H, or TBS", credits: 1)
@SSandH.requirements.find_or_create_by(name:"SS, H, or TBS", credits: 1)

@FreeElec.requirements.find_or_create_by(name:"Free Elective", credits: 1)
@FreeElec.requirements.find_or_create_by(name:"Free Elective", credits: 1)

###########################EE############################

@EE = Major.find_or_create_by(name: "Electrical Engineering", total_required:40)

@MathandNatSci = @EE.curriculum_fields.find_or_create_by!(name:"Math and Natural Science" , total_required:10.5)
@Eng = @EE.curriculum_fields.find_or_create_by(name:"Engineering" , total_required:16)
@ProfElec = @EE.curriculum_fields.find_or_create_by(name:"Professional Electives" , total_required:4)
@SSandH = @EE.curriculum_fields.find_or_create_by(name:"Social Science and Humanities" , total_required:7)
@FreeElec =@EE.curriculum_fields.find_or_create_by(name:"Free Elective" , total_required:3)

@MathandNatSci.requirements.find_or_create_by(name: "MATH 104", credits: 1)
@MathandNatSci.requirements.find_or_create_by(name: "MATH 114", credits: 1)
@MathandNatSci.requirements.find_or_create_by(name: "MATH 240", credits: 1)
@MathandNatSci.requirements.find_or_create_by(name: "ESE 301", credits: 1)
@MathandNatSci.requirements.find_or_create_by(name: "Math Elective", credits: 1)
@MathandNatSci.requirements.find_or_create_by(name: "PHYS 140, 150, or 170", credits: 1)
@MathandNatSci.requirements.find_or_create_by(name: "PHYS 151 or PHYS 171", credits: 1.5)
@MathandNatSci.requirements.find_or_create_by(name: "CHEM 101 or BIOL 101 or BIOL 121", credits: 1)
@MathandNatSci.requirements.find_or_create_by(name: "Natural Science Lab", credits: 0.5)
@MathandNatSci.requirements.find_or_create_by(name: "Math or Natural Science Elective", credits: 1)

@Eng.requirements.find_or_create_by(name:"CIS 110 or EAS 105", credits: 1)
@Eng.requirements.find_or_create_by(name:"ESE 111", credits: 1)
@Eng.requirements.find_or_create_by(name:"ESE 215", credits: 1.5)
@Eng.requirements.find_or_create_by(name:"ESE 218", credits: 1.5)
@Eng.requirements.find_or_create_by(name:"ESE 224", credits: 1.5)
@Eng.requirements.find_or_create_by(name:"CIS 120 or 240", credits: 1)
@Eng.requirements.find_or_create_by(name:"ESE Elective", credits: 1)
@Eng.requirements.find_or_create_by(name:"Advanced Elective", credits: 1)
@Eng.requirements.find_or_create_by(name:"Advanced Elective", credits: 1)
@Eng.requirements.find_or_create_by(name:"Advanced Elective", credits: 1)
@Eng.requirements.find_or_create_by(name:"Advanced Elective", credits: 1.5)
@Eng.requirements.find_or_create_by(name:"ESE Lab", credits: 1)
@Eng.requirements.find_or_create_by(name:"ESE 450", credits: 1)
@Eng.requirements.find_or_create_by(name:"ESE 451", credits: 1)


@ProfElec.requirements.find_or_create_by(name:"Engineering", credits: 1)
@ProfElec.requirements.find_or_create_by(name:"Math, Science, or Engineering", credits: 1)
@ProfElec.requirements.find_or_create_by(name:"Math, Science, or Engineering", credits: 1)
@ProfElec.requirements.find_or_create_by(name:"ESE 400, EAS 545 or EAS 595", credits: 1)

@SSandH.requirements.find_or_create_by(name:"EAS 203", credits: 1)
@SSandH.requirements.find_or_create_by(name:"Social Science", credits: 1)
@SSandH.requirements.find_or_create_by(name:"Humanities", credits: 1)
@SSandH.requirements.find_or_create_by(name:"Humanities", credits: 1)
@SSandH.requirements.find_or_create_by(name:"SS or H", credits: 1)
@SSandH.requirements.find_or_create_by(name:"SS, H, or TBS", credits: 1)
@SSandH.requirements.find_or_create_by(name:"SS, H, or TBS", credits: 1)

@FreeElec.requirements.find_or_create_by(name:"Free Elective", credits: 1)
@FreeElec.requirements.find_or_create_by(name:"Free Elective", credits: 1)
@FreeElec.requirements.find_or_create_by(name:"Free Elective", credits: 1)

###########################CBE############################
@CBE = Major.find_or_create_by(name: "Chemical Biomolecular Engineering", total_required:41)

@Math = @CBE.curriculum_fields.find_or_create_by!(name:"Math" , total_required:4)
@NatSci = @CBE.curriculum_fields.find_or_create_by(name:"Natural Science" , total_required:9)
@Eng = @CBE.curriculum_fields.find_or_create_by(name:"Engineering" , total_required:14)
@TechElec = @CBE.curriculum_fields.find_or_create_by(name:"Tech Elective" , total_required:4)
@SSandH = @CBE.curriculum_fields.find_or_create_by(name:"Social Science and Humanities" , total_required:7)
@FreeElec =@CBE.curriculum_fields.find_or_create_by(name:"Free Elective" , total_required:3)

@Math.requirements.find_or_create_by(name: "MATH 104", credits: 1)
@Math.requirements.find_or_create_by(name: "MATH 114", credits: 1)
@Math.requirements.find_or_create_by(name: "MATH 240", credits: 1)
@Math.requirements.find_or_create_by(name: "MATH 241", credits: 1)

@NatSci.requirements.find_or_create_by(name: "PHYS 140 or PHYS 150", credits: 1.5)
@NatSci.requirements.find_or_create_by(name: "PHYS 141 or PHYS 151", credits: 1.5)
@NatSci.requirements.find_or_create_by(name: "CHEM 101", credits: 1)
@NatSci.requirements.find_or_create_by(name: "CHEM 053", credits: 0.5)
@NatSci.requirements.find_or_create_by(name: "CHEM 102", credits: 1)
@NatSci.requirements.find_or_create_by(name: "CHEM 054", credits: 0.5)
@NatSci.requirements.find_or_create_by(name: "CHEM 221 or MSE 221", credits: 1)
@NatSci.requirements.find_or_create_by(name: "CHEM 241", credits: 1)
@NatSci.requirements.find_or_create_by(name: "CHEM 242 or MSE 251", credits: 1)

@Eng.requirements.find_or_create_by(name:"EAS 105", credits: 1)
@Eng.requirements.find_or_create_by(name:"CBE 160", credits: 1)
@Eng.requirements.find_or_create_by(name:"CBE 230", credits: 1)
@Eng.requirements.find_or_create_by(name:"CBE 231", credits: 1)
@Eng.requirements.find_or_create_by(name:"CBE 350", credits: 1)
@Eng.requirements.find_or_create_by(name:"CBE 351", credits: 1)
@Eng.requirements.find_or_create_by(name:"CBE 353", credits: 1)
@Eng.requirements.find_or_create_by(name:"CBE 371", credits: 1)
@Eng.requirements.find_or_create_by(name:"CBE 400", credits: 1)
@Eng.requirements.find_or_create_by(name:"CBE 410", credits: 1)
@Eng.requirements.find_or_create_by(name:"CBE 451", credits: 1)
@Eng.requirements.find_or_create_by(name:"CBE 459", credits: 1)
@Eng.requirements.find_or_create_by(name:"CBE 460", credits: 1)
@Eng.requirements.find_or_create_by(name:"CBE Elective", credits: 1)
@Eng.requirements.find_or_create_by(name:"CBE Elective", credits: 1)

@TechElec.requirements.find_or_create_by(name:"Engineering", credits: 1)
@TechElec.requirements.find_or_create_by(name:"Tech Elective", credits: 1)
@TechElec.requirements.find_or_create_by(name:"Tech Elective", credits: 1)
@TechElec.requirements.find_or_create_by(name:"CBE 480 or CHEM 223 or CHEM 245", credits: 1)

@SSandH.requirements.find_or_create_by(name:"Social Science", credits: 1)
@SSandH.requirements.find_or_create_by(name:"Social Science", credits: 1)
@SSandH.requirements.find_or_create_by(name:"Humanities", credits: 1)
@SSandH.requirements.find_or_create_by(name:"Humanities", credits: 1)
@SSandH.requirements.find_or_create_by(name:"SS or H", credits: 1)
@SSandH.requirements.find_or_create_by(name:"SS, H, or TBS", credits: 1)
@SSandH.requirements.find_or_create_by(name:"SS, H, or TBS", credits: 1)

@FreeElec.requirements.find_or_create_by(name:"Free Elective", credits: 1)
@FreeElec.requirements.find_or_create_by(name:"Free Elective", credits: 1)
@FreeElec.requirements.find_or_create_by(name:"Free Elective", credits: 1)

###########################MSE############################
@MSE = Major.find_or_create_by(name: "Materials Science and Engineering", total_required:40)

@Math = @MSE.curriculum_fields.find_or_create_by!(name:"Math" , total_required:5)
@NatSci = @MSE.curriculum_fields.find_or_create_by(name:"Natural Science" , total_required:6)
@Eng = @MSE.curriculum_fields.find_or_create_by(name:"Engineering" , total_required:14)
@TechElec = @MSE.curriculum_fields.find_or_create_by(name:"Technical Electives" , total_required:5)
@SSandH = @MSE.curriculum_fields.find_or_create_by(name:"Social Science and Humanities" , total_required:7)
@FreeElec =@MSE.curriculum_fields.find_or_create_by(name:"Free Elective" , total_required:3)

@Math.requirements.find_or_create_by(name: "MATH 104", credits: 1)
@Math.requirements.find_or_create_by(name: "MATH 114", credits: 1)
@Math.requirements.find_or_create_by(name: "MATH 240", credits: 1)
@Math.requirements.find_or_create_by(name: "MATH 241", credits: 1)
@Math.requirements.find_or_create_by(name: "Mathematics", credits: 1)

@NatSci.requirements.find_or_create_by(name: "PHYS 140", credits: 1)
@NatSci.requirements.find_or_create_by(name: "PHYS 141", credits: 1)
@NatSci.requirements.find_or_create_by(name: "CHEM 101", credits: 1)
@NatSci.requirements.find_or_create_by(name: "CHEM 053", credits: 0.5)
@NatSci.requirements.find_or_create_by(name: "CHEM 102", credits: 1)
@NatSci.requirements.find_or_create_by(name: "CHEM 054", credits: 0.5)
@NatSci.requirements.find_or_create_by(name: "Natural Science (BIOL 121 recommended)", credits: 1)

@Eng.requirements.find_or_create_by(name:"MSE 215", credits: 1)
@Eng.requirements.find_or_create_by(name:"MSE 220", credits: 1)
@Eng.requirements.find_or_create_by(name:"MSE 221", credits: 1)
@Eng.requirements.find_or_create_by(name:"MSE 250", credits: 1)
@Eng.requirements.find_or_create_by(name:"MSE 260", credits: 1)
@Eng.requirements.find_or_create_by(name:"MSE 330", credits: 1)
@Eng.requirements.find_or_create_by(name:"MSE 360", credits: 1)
@Eng.requirements.find_or_create_by(name:"MSE 393", credits: 1)
@Eng.requirements.find_or_create_by(name:"MSE 405", credits: 1)
@Eng.requirements.find_or_create_by(name:"MSE 440", credits: 1)
@Eng.requirements.find_or_create_by(name:"MSE 495", credits: 1)
@Eng.requirements.find_or_create_by(name:"MSE 496", credits: 1)
@Eng.requirements.find_or_create_by(name:"Engineering", credits: 1)
@Eng.requirements.find_or_create_by(name:"Engineering", credits: 1)

@TechElec.requirements.find_or_create_by(name:"Tech Elective (Engineering)", credits: 1)
@TechElec.requirements.find_or_create_by(name:"Tech Elective", credits: 1)
@TechElec.requirements.find_or_create_by(name:"Tech Elective", credits: 1)
@TechElec.requirements.find_or_create_by(name:"Tech Elective", credits: 1)
@TechElec.requirements.find_or_create_by(name:"Tech Elective", credits: 1)

@SSandH.requirements.find_or_create_by(name:"Social Science", credits: 1)
@SSandH.requirements.find_or_create_by(name:"Social Science", credits: 1)
@SSandH.requirements.find_or_create_by(name:"Humanities", credits: 1)
@SSandH.requirements.find_or_create_by(name:"Humanities", credits: 1)
@SSandH.requirements.find_or_create_by(name:"SS or H", credits: 1)
@SSandH.requirements.find_or_create_by(name:"SS, H, or TBS", credits: 1)
@SSandH.requirements.find_or_create_by(name:"SS, H, or TBS", credits: 1)

@FreeElec.requirements.find_or_create_by(name:"Free Elective", credits: 1)
@FreeElec.requirements.find_or_create_by(name:"Free Elective", credits: 1)
@FreeElec.requirements.find_or_create_by(name:"Free Elective", credits: 1)

###########################NETS############################

@NETS = Major.find_or_create_by(name: "Networked and Social Systems", total_required:40)

@MathandNatSci = @NETS.curriculum_fields.find_or_create_by!(name:"Math and Natural Science" , total_required:10)
@Eng = @NETS.curriculum_fields.find_or_create_by(name:"Engineering" , total_required:14)
@TechElec = @NETS.curriculum_fields.find_or_create_by(name:"Tech Elective" , total_required:6)
@SSandH = @NETS.curriculum_fields.find_or_create_by(name:"Social Science and Humanities" , total_required:7)
@FreeElec =@NETS.curriculum_fields.find_or_create_by(name:"Free Elective" , total_required:3)

@MathandNatSci.requirements.find_or_create_by(name: "MATH 104", credits: 1)
@MathandNatSci.requirements.find_or_create_by(name: "MATH 114", credits: 1)
@MathandNatSci.requirements.find_or_create_by(name: "MATH 240", credits: 1)
@MathandNatSci.requirements.find_or_create_by(name: "CIS 160", credits: 1)
@MathandNatSci.requirements.find_or_create_by(name: "EAS 205 or MATH312", credits: 1)
@MathandNatSci.requirements.find_or_create_by(name: "EAS 301, STAT 430, or MATH 430", credits: 1)
@MathandNatSci.requirements.find_or_create_by(name: "PHYS 150 or PHYS 170", credits: 1.5)
@MathandNatSci.requirements.find_or_create_by(name: "PHYS 151 or PHYS 171", credits: 1.5)
@MathandNatSci.requirements.find_or_create_by(name: "Natural Science Elective", credits: 1)

@Eng.requirements.find_or_create_by(name:"CIS 110", credits: 1)
@Eng.requirements.find_or_create_by(name:"CIS 120", credits: 1)
@Eng.requirements.find_or_create_by(name:"CIS 121", credits: 1)
@Eng.requirements.find_or_create_by(name:"CIS 320", credits: 1)
@Eng.requirements.find_or_create_by(name:"ESE 210", credits: 1)
@Eng.requirements.find_or_create_by(name:"ESE 303", credits: 1)
@Eng.requirements.find_or_create_by(name:"ESE 304", credits: 1)
@Eng.requirements.find_or_create_by(name:"NETS 112", credits: 1)
@Eng.requirements.find_or_create_by(name:"NETS 150", credits: 1)
@Eng.requirements.find_or_create_by(name:"NETS 212", credits: 1)
@Eng.requirements.find_or_create_by(name:"NETS 312", credits: 1)
@Eng.requirements.find_or_create_by(name:"NETS 412", credits: 1)
@Eng.requirements.find_or_create_by(name:"CIS 400 or ESE 450", credits: 1)
@Eng.requirements.find_or_create_by(name:"CIS 401 or ESE 451", credits: 1)

@TechElec.requirements.find_or_create_by(name:"Tech Elective (Depth)", credits: 1)
@TechElec.requirements.find_or_create_by(name:"Tech Elective (Depth)", credits: 1)
@TechElec.requirements.find_or_create_by(name:"Tech Elective (Depth)", credits: 1)
@TechElec.requirements.find_or_create_by(name:"Tech Elective", credits: 1)
@TechElec.requirements.find_or_create_by(name:"Tech Elective", credits: 1)
@TechElec.requirements.find_or_create_by(name:"Tech Elective", credits: 1)

@SSandH.requirements.find_or_create_by(name:"ECON 101", credits: 1)
@SSandH.requirements.find_or_create_by(name:"ECON 212", credits: 1)
@SSandH.requirements.find_or_create_by(name:"Humanities", credits: 1)
@SSandH.requirements.find_or_create_by(name:"Humanities", credits: 1)
@SSandH.requirements.find_or_create_by(name:"SS or H", credits: 1)
@SSandH.requirements.find_or_create_by(name:"SS, H, or TBS", credits: 1)
@SSandH.requirements.find_or_create_by(name:"SS, H, or TBS", credits: 1)

@FreeElec.requirements.find_or_create_by(name:"Free Elective", credits: 1)
@FreeElec.requirements.find_or_create_by(name:"Free Elective", credits: 1)
@FreeElec.requirements.find_or_create_by(name:"Free Elective", credits: 1)

###########################EE############################

@SSE = Major.find_or_create_by(name: "Systems Science and Engineering", total_required:40)

@MathandNatSci = @SSE.curriculum_fields.find_or_create_by!(name:"Math and Natural Science" , total_required:10)
@Eng = @SSE.curriculum_fields.find_or_create_by(name:"Engineering" , total_required:15)
@ProfElec = @SSE.curriculum_fields.find_or_create_by(name:"Professional Electives" , total_required:5)
@SSandH = @SSE.curriculum_fields.find_or_create_by(name:"Social Science and Humanities" , total_required:7)
@FreeElec =@SSE.curriculum_fields.find_or_create_by(name:"Free Elective" , total_required:3)

@MathandNatSci.requirements.find_or_create_by(name: "MATH 104", credits: 1)
@MathandNatSci.requirements.find_or_create_by(name: "MATH 114", credits: 1)
@MathandNatSci.requirements.find_or_create_by(name: "MATH 240", credits: 1)
@MathandNatSci.requirements.find_or_create_by(name: "ESE 301", credits: 1)
@MathandNatSci.requirements.find_or_create_by(name: "ESE 302", credits: 1)
@MathandNatSci.requirements.find_or_create_by(name: "PHYS 140, 150, or 170", credits: 1)
@MathandNatSci.requirements.find_or_create_by(name: "PHYS 141, 151 or PHYS 171", credits: 1)
@MathandNatSci.requirements.find_or_create_by(name: "CHEM 101 or BIOL 101 or BIOL 121", credits: 1)
@MathandNatSci.requirements.find_or_create_by(name: "MATH 312 or EAS 205", credits: 1)
@MathandNatSci.requirements.find_or_create_by(name: "Natural Science Lab", credits: 0.5)
@MathandNatSci.requirements.find_or_create_by(name: "Natural Science Lab", credits: 0.5)

@Eng.requirements.find_or_create_by(name:"CIS 110 or EAS 105", credits: 1)
@Eng.requirements.find_or_create_by(name:"ESE 111", credits: 1)
@Eng.requirements.find_or_create_by(name:"CIS 120", credits: 1)
@Eng.requirements.find_or_create_by(name:"ESE 204", credits: 1)
@Eng.requirements.find_or_create_by(name:"ESE 210", credits: 1)
@Eng.requirements.find_or_create_by(name:"ESE 224", credits: 1.5)
@Eng.requirements.find_or_create_by(name:"ESE 303", credits: 1)
@Eng.requirements.find_or_create_by(name:"ISE Elective", credits: 1)
@Eng.requirements.find_or_create_by(name:"ISE Elective", credits: 1)
@Eng.requirements.find_or_create_by(name:"ISE Elective", credits: 1)
@Eng.requirements.find_or_create_by(name:"CIS 350, CIS 441, or ESE 590", credits: 1)
@Eng.requirements.find_or_create_by(name:"ESE 350", credits: 1.5)
@Eng.requirements.find_or_create_by(name:"ESE 450", credits: 1)
@Eng.requirements.find_or_create_by(name:"ESE 451", credits: 1)

@ProfElec.requirements.find_or_create_by(name:"TME Engineering Elective", credits: 1)
@ProfElec.requirements.find_or_create_by(name:"TME Elective", credits: 1)
@ProfElec.requirements.find_or_create_by(name:"SPA Elective", credits: 1)
@ProfElec.requirements.find_or_create_by(name:"SPA Elective", credits: 1)

@SSandH.requirements.find_or_create_by(name:"EAS 203", credits: 1)
@SSandH.requirements.find_or_create_by(name:"Social Science", credits: 1)
@SSandH.requirements.find_or_create_by(name:"Humanities", credits: 1)
@SSandH.requirements.find_or_create_by(name:"Humanities", credits: 1)
@SSandH.requirements.find_or_create_by(name:"SS or H", credits: 1)
@SSandH.requirements.find_or_create_by(name:"SS, H, or TBS", credits: 1)
@SSandH.requirements.find_or_create_by(name:"SS, H, or TBS", credits: 1)

@FreeElec.requirements.find_or_create_by(name:"Free Elective", credits: 1)
@FreeElec.requirements.find_or_create_by(name:"Free Elective", credits: 1)
@FreeElec.requirements.find_or_create_by(name:"Free Elective", credits: 1)
